### ISSUE TITLE
ModuleNotFoundError: No module named 'bilix'

### ISSUE THREAD

**Issue by andynvt** [dxsooo/VideoDownload#18]
```
 python3 download.py -u https://www.ixigua.com/7168489715828851215\?id\=7111665255088685605\&logTag\=5612bf2fc2b05e20c181
Traceback (most recent call last):
  File "/Users/andy/Downloads/VideoDownload/download.py", line 4, in <module>
    from download_bilibili import download_bilibili_video, is_bilibili_video
  File "/Users/andy/Downloads/VideoDownload/download_bilibili.py", line 6, in <module>
    import bilix.api.bilibili as api
ModuleNotFoundError: No module named 'bilix'
```

**Comment by dxsooo** [comment]
Hi, it seems that you miss the lines:
```bash
poetry export -f requirements.txt | pip install -r /dev/stdin
```

This cmd would help install all the dep python pkgs.

Also, you can install pkgs by pip directly if you don't have poetry:
```bash
pip install you-get yt-dlp bilix
```
and call with: (notice that the url should not include any parameter)
```bash
python3 download.py -u https://www.ixigua.com/7168489715828851215
```

---
## however

Downloading ixigua depends on `you-get`, but the current version(0.4.1650) not worked. I just create a PR(https://github.com/soimort/you-get/pull/3001) to fix it. I would update my project once the newest you-get released.

**Comment by gsxgmpkt9020** [comment]
> 

`poetry export -f requirements.txt | pip install -r /dev/stdin`

This code is only for unix not for cmd or power shell on windows.

I ran  `poetry export -f requirements.txt --output requirements.txt` & `pip install -r requirements.txt`

but got `Ignoring brotlicffi: markers 'python_version >= "3.8" and python_version < "4.0" and platform_python_implementation != "CPython"' don't match your environment
Ignoring cffi: markers 'python_version >= "3.8" and python_version < "4.0" and platform_python_implementation != "CPython"' don't match your environment
Ignoring pycparser: markers 'python_version >= "3.8" and python_version < "4.0" and platform_python_implementation != "CPython"' don't match your environment
Collecting you-get@ git+https://github.com/soimort/you-get@HEAD
ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
    you-get@ git+https://github.com/soimort/you-get@HEAD from git+https://github.com/soimort/you-get@HEAD (from -r requirements.txt (line 460))`


My py version is 3.9.4

**Comment by dxsooo** [comment]
> > 
> 
> `poetry export -f requirements.txt | pip install -r /dev/stdin`
> 
> This code is only for unix not for cmd or power shell on windows.
> 
> I ran `poetry export -f requirements.txt --output requirements.txt` & `pip install -r requirements.txt`
> 
> but got `Ignoring brotlicffi: markers 'python_version >= "3.8" and python_version < "4.0" and platform_python_implementation != "CPython"' don't match your environment Ignoring cffi: markers 'python_version >= "3.8" and python_version < "4.0" and platform_python_implementation != "CPython"' don't match your environment Ignoring pycparser: markers 'python_version >= "3.8" and python_version < "4.0" and platform_python_implementation != "CPython"' don't match your environment Collecting you-get@ git+https://github.com/soimort/you-get@HEAD ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories: you-get@ git+https://github.com/soimort/you-get@HEAD from git+https://github.com/soimort/you-get@HEAD (from -r requirements.txt (line 460))`
> 
> My py version is 3.9.4

Hi, thank you for point out the install problems for non-poetry envs

I have updated my code and you can run after pull:
```powershell
poetry export -f requirements.txt --output requirements.txt --without-hashes
pip install -r requirements.txt
```
again to install all deps
